name: "C++ Lint"

on: [push]

jobs:
  cpp-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: action-cpp-lint
      uses: CyberZHG/github-action-cpp-lint@0.0.2
      with:
        args: "--recursive ./src/arduino/"
